package su.knst.crypto.tests.core.render;

import org.junit.jupiter.api.Test;
import su.knst.crypto.core.render.QrCodec;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Scans the synthetic "photographed QR code" fixtures generated by
 * {@code tools/generate_qr_photo_fixtures.py} through the real `qr scan` command
 * (`SimpleQRCodeWorker`) and checks the decoded text against each file's name -
 * every fixture is named after its own QR payload, so no separate ground-truth
 * file is needed.
 * <p>
 * The fixtures simulate an actual phone photo of a printed QR code: tilted in 3D,
 * varying distance/size, out of focus, sensor noise, uneven lighting, JPEG
 * compression - not clean synthetic renders.
 * <p>
 * The fixtures are split into two directories by {@code tools/split_fixtures_by_opencv.py},
 * using OpenCV's QR decoder (a completely different implementation from ZXing) as an
 * independent referee:
 * <ul>
 *     <li>{@code qr_photo_fixtures/} - OpenCV itself decodes these correctly, so they are
 *     confirmed readable in principle. This is the real characterization test: it reports
 *     exactly what fraction the current scanner recovers rather than asserting every photo
 *     must decode.</li>
 *     <li>{@code qr_photo_fixtures_hard/} - OpenCV also fails on these. Kept on purpose as an
 *     adversarial control set: since this is a difficulty level nothing is expected to solve,
 *     the printed breakdown for it should show real "FAILED" entries. If it ever showed 100%
 *     passing, that would mean the pass/fail check here is broken (e.g. quietly matching
 *     everything) rather than that the scanner improved.</li>
 * </ul>
 * <p>
 * Regenerate everything with:
 * {@code python3 tools/generate_qr_photo_fixtures.py src/test/resources/qr_photo_fixtures 100 &&
 * python3 tools/split_fixtures_by_opencv.py}
 */
class QrCodecFixtureScanTest {

    static final Path READABLE_FIXTURES_DIR = Path.of("src/test/resources/qr_photo_fixtures");
    static final Path HARD_FIXTURES_DIR = Path.of("src/test/resources/qr_photo_fixtures_hard");

    @Test
    void scanConfirmedReadableFixtures() throws IOException {
        ScanReport report = scanDirectory(READABLE_FIXTURES_DIR, "confirmed-readable");

        // sanity guard only, not a quality bar: catches total scanner breakage (e.g. an
        // exception thrown on every input) without pinning down an exact recognition rate
        // that would just make this test flaky as the random fixture set changes.
        assertTrue(report.ok > 0,
                "scanner failed to decode a single photo from the confirmed-readable set " +
                        "(" + report.ok + "/" + report.total + ")");
    }

    @Test
    void scanAdversarialHardFixtures() throws IOException {
        // no ok > 0 assertion here on purpose: OpenCV itself can't read these, so the
        // scanner failing on them too is the expected, uninteresting outcome. The point
        // of this test is only to make the FAILED entries show up in the printed report,
        // proving scanDirectory()/the pass check can and does produce real failures
        // instead of unconditionally reporting success.
        scanDirectory(HARD_FIXTURES_DIR, "adversarial-hard-control");
    }

    private ScanReport scanDirectory(Path dir, String label) throws IOException {
        assertTrue(Files.isDirectory(dir),
                "fixtures not found at " + dir.toAbsolutePath() +
                        " - generate them with tools/generate_qr_photo_fixtures.py " +
                        "and tools/split_fixtures_by_opencv.py first");

        List<Path> fixtures;
        try (Stream<Path> files = Files.list(dir)) {
            fixtures = files.filter(Files::isRegularFile).sorted().toList();
        }

        assertFalse(fixtures.isEmpty(), "no fixture files found in " + dir.toAbsolutePath());

        List<String> failures = new ArrayList<>();
        int ok = 0;

        for (Path fixture : fixtures) {
            String fileName = fixture.getFileName().toString();
            String expectedPayload = fileName.substring(0, fileName.lastIndexOf('.'));

            String decoded = QrCodec.decode(fixture);

            if (expectedPayload.equals(decoded)) {
                ok++;
            } else {
                failures.add(fileName + " -> " + (decoded == null ? "no code found" : "decoded mismatch: '" + decoded + "'"));
            }
        }

        int total = fixtures.size();
        double rate = 100.0 * ok / total;

        System.out.println("\n=== QR photo fixture scan results [" + label + "] ===");
        System.out.printf("Decoded correctly: %d / %d (%.1f%%)%n", ok, total, rate);
        if (!failures.isEmpty()) {
            System.out.println("Failed files:");
            failures.forEach(f -> System.out.println("  " + f));
        }
        System.out.println("======================================\n");

        return new ScanReport(ok, total);
    }

    private record ScanReport(int ok, int total) {
    }
}
