#!/usr/bin/env python3
"""
Splits the fixtures generated by generate_qr_photo_fixtures.py into two folders using
OpenCV's QR decoder (a different implementation from ZXing) as an independent referee:

  - qr_photo_fixtures/          images OpenCV itself can decode correctly - a "should be
                                 readable by any competent scanner" set.
  - qr_photo_fixtures_hard/     images OpenCV also fails on - kept as a deliberately
                                 adversarial control set. It exists so the Java test suite
                                 has known cases that are NOT expected to pass, to prove the
                                 test assertions actually discriminate pass from fail instead
                                 of rubber-stamping everything green.

Usage:
    python3 tools/split_fixtures_by_opencv.py [source_dir] [readable_dir] [hard_dir]

Requires: opencv-python-headless
    python3 -m pip install --user opencv-python-headless
"""
import glob
import os
import shutil
import sys

import cv2

SOURCE_DIR = sys.argv[1] if len(sys.argv) > 1 else "src/test/resources/qr_photo_fixtures"
READABLE_DIR = sys.argv[2] if len(sys.argv) > 2 else "src/test/resources/qr_photo_fixtures"
HARD_DIR = sys.argv[3] if len(sys.argv) > 3 else "src/test/resources/qr_photo_fixtures_hard"


def main():
    files = sorted(glob.glob(os.path.join(SOURCE_DIR, "*")))
    if not files:
        print(f"No fixture files found in {SOURCE_DIR}")
        sys.exit(1)

    os.makedirs(READABLE_DIR, exist_ok=True)
    os.makedirs(HARD_DIR, exist_ok=True)

    detector = cv2.QRCodeDetector()
    readable = 0
    hard = 0

    for path in files:
        expected = os.path.splitext(os.path.basename(path))[0]
        img = cv2.imread(path)
        data, _points, _ = detector.detectAndDecode(img)

        target_dir = READABLE_DIR if data == expected else HARD_DIR
        dest = os.path.join(target_dir, os.path.basename(path))

        if os.path.abspath(dest) != os.path.abspath(path):
            shutil.move(path, dest)

        if data == expected:
            readable += 1
        else:
            hard += 1

    print(f"{readable} fixtures confirmed readable -> {READABLE_DIR}")
    print(f"{hard} fixtures OpenCV also couldn't read -> {HARD_DIR}")


if __name__ == "__main__":
    main()
