#!/usr/bin/env python3
"""
Independent sanity check for the fixtures generated by generate_qr_photo_fixtures.py:
decodes every fixture with OpenCV's QR decoder (a completely different implementation
from ZXing, which su.knst.crypto.utils.codes.SimpleQRCodeWorker uses) so a low score
from the Java-side test can be attributed to the scanner, not to broken fixtures.

Usage:
    python3 tools/verify_fixtures_with_opencv.py [fixtures_dir]

Requires: opencv-python-headless
    python3 -m pip install --user opencv-python-headless
"""
import glob
import os
import sys

import cv2

FIXTURES_DIR = sys.argv[1] if len(sys.argv) > 1 else "src/test/resources/qr_photo_fixtures"


def main():
    files = sorted(glob.glob(os.path.join(FIXTURES_DIR, "*")))
    if not files:
        print(f"No fixture files found in {FIXTURES_DIR}")
        sys.exit(1)

    detector = cv2.QRCodeDetector()
    ok = 0
    failures = []

    for path in files:
        expected = os.path.splitext(os.path.basename(path))[0]
        img = cv2.imread(path)
        data, _points, _ = detector.detectAndDecode(img)

        if data == expected:
            ok += 1
        else:
            failures.append((os.path.basename(path), data))

    print(f"{ok}/{len(files)} decoded correctly by OpenCV's QRCodeDetector")
    if failures:
        print("Failed files:")
        for name, data in failures:
            print(f"  {name} -> {data!r}")


if __name__ == "__main__":
    main()
